steps:
  # create container with Poland dump
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--name', 'overpass_step1',
           '-e', 'OVERPASS_META=yes',
           '-e', 'OVERPASS_MODE=init',
           '-e', 'OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/poland-latest.osm.bz2',
           '-e', 'OVERPASS_DIFF_URL=http://download.geofabrik.de/europe/poland-updates/',
           '-e', 'OVERPASS_COMPRESSION=lz4',
           '-it',
           'wiktorn/overpass',
           '/bin/bash -c "/app/docker-entrypoint.sh && /app/bin/update_overpass.sh && /app/bin/osm3s_query --progress --rules  < /db/db/rules/areas.osm3s"',
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['cp', 'supervisord.conf', 'overpass_step1:/etc/supervisor/supervisord.conf']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['commit',
           '-r', 'CMD /app/docker-entrypoint.sh',
           'overpass_step1', 'gcr.io/osm-vink/overpass-poland:latest',
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/osm-vink/overpass-poland:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'overpass-poland',
           '--image=gcr.io/osm-vink/overpass-poland:latest',
           '--region=us-central1',
           '--memory=1024Mi',
           '--allow-unauthenticated',
    ]

timeout: 3600s